// Generated by CoffeeScript 1.4.0
(function() {
  var fade;

  fade = function(id) {
    return $(id).delay(5000).fadeOut("slow");
  };

  $(document).ready(function() {
    return $(document).keypress(function(e) {
      var value;
      value = void 0;
      if (e.which === 13) {
        value = $("#colorin").val();
        if (value.match(/^[0-9]{6}$/)) {
          value = "#" + value;
          $("body").css("background-color", value);
          return $("#warning").hide();
        } else {
          $("#warning").show();
          return fade("#warning");
        }
      }
    });
  });

}).call(this);
