// Generated by CoffeeScript 1.4.0
(function() {
  var books, countries, gray, photos, reveal, ungray, _gaq;

  _gaq = _gaq || [];

  _gaq.push(["_setAccount", "UA-26483099-2"]);

  _gaq.push(["_setDomainName", "yifanwu.net"]);

  _gaq.push(["_trackPageview"]);

  (function() {
    var ga, s;
    ga = document.createElement("script");
    ga.type = "text/javascript";
    ga.async = true;
    ga.src = ("https:" === document.location.protocol ? "https://ssl" : "http://www") + ".google-analytics.com/ga.js";
    s = document.getElementsByTagName("script")[0];
    return s.parentNode.insertBefore(ga, s);
  })();

  ungray = function(id) {
    return $(id).animate({
      opacity: 1.0
    }, 500);
  };

  gray = function(id) {
    return $(id).animate({
      opacity: 0.5
    }, 500);
  };

  reveal = function(id, array) {
    var i, _results;
    i = 0;
    _results = [];
    while (i < array.length) {
      if (id !== array[i]) {
        gray(array[i]);
        $(array[i] + "_details").hide();
      } else {
        ungray(array[i]);
        $(array[i] + "_details").show();
      }
      _results.push(i++);
    }
    return _results;
  };

  countries = ["#america", "#china", "#india", "#mexico", "#uk", "#taiwan"];

  books = ["#intothewild", "#1984", "#blink", "#thecatcher"];

  photos = ["#charles", "#harvard", "#seattle", "#india", "#mexico", "#newbedford"];

  $(document).ready(function() {
    /* traveling
    */
    $("#india").click(function() {
      return reveal("#india", countries);
    });
    $("#mexico").click(function() {
      return reveal("#mexico", countries);
    });
    $("#china").click(function() {
      return reveal("#china", countries);
    });
    $("#taiwan").click(function() {
      return reveal("#taiwan", countries);
    });
    $("#charles").click(function() {
      return reveal("#charles", photos);
    });
    $("#harvard").click(function() {
      return reveal("#harvard", photos);
    });
    $("#newbedford").click(function() {
      return reveal("#newbedford", photos);
    });
    $("#seattle").click(function() {
      return reveal("#seattle", photos);
    });
    $("#india").click(function() {
      return reveal("#india", photos);
    });
    $("#mexico").click(function() {
      return reveal("#mexico", photos);
    });
    /* books
    */

    return $("#intothewild").click(function() {
      return reveal("#intothewild", books);
    });
  });

}).call(this);
