// Generated by CoffeeScript 1.4.0
(function() {
  var fade;

  fade = function(id) {
    return $(id).delay(5000).fadeOut("slow");
  };

  $(document).ready(function() {
    return $(document).keypress(function(e) {
      var regexIn, strIn, value;
      value = void 0;
      if (e.which === 13) {
        regexIn = $("#regexin").val();
        regexIn = "/" + regexIn + "/";
        strIn = $("#strin").val();
        if (strIn.match(regexIn)) {
          $("#cong").show();
          $("#warning").hide();
          return alert(regexIn);
        } else {
          alert(regexIn);
          $("#warning").show();
          return fade("#warning");
        }
      }
    });
  });

}).call(this);
